name: Deploy

on:
  schedule:
    - cron: '*/30 6-8 * * *'
    - cron: '*/30 18-20 * * *'
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install R
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
        sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/'
        sudo apt update
        sudo apt install -y r-base
    - name: Install base dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential && sudo apt-get install -y libcurl4-gnutls-dev && sudo apt-get install -y libxml2-dev && sudo apt-get install -y libssl-dev && sudo apt-get install -y libudunits2-dev && sudo apt-get install libprotobuf-dev
    - name: Download phantomjs
      run: wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
    - name: Install phantomjs
      run: |
        sudo tar xjvf phantomjs-2.1.1-linux-x86_64.tar.bz2 -C /usr/local/share/
        sudo ln -f -s /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin
    - name: Install needed packages
      run: |
        sudo Rscript -e "install.packages('devtools')"
        sudo Rscript -e "install.packages('tidyverse')"
        sudo Rscript -e "devtools::install_github('datasketch/geodata')"
        sudo Rscript -e "devtools::install_github('randommonkey/lfltmagic')"
    - name: Run script
      run: sudo Rscript source_files.R
    - name: Commit changes
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email action@github.com
        git add .
        git commit --allow-empty -m 'Updated build'
        git push origin master
